There has been probles calculating the FC, so I am going to re do this

In [162]:
import pandas as pd
import numpy as np
from openpyxl.utils.datetime import to_excel

In [163]:
raw_abundances = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/Renamed.xlsx", sheet_name="raw_abundances_matrix")
raw_abundances

,protein_ID,prot_name,IDcolumn,CON,REV,site,isotopeLabel,EGFnINS1_rep1,EGFnINS1_rep2,EGFnINS1_rep3,...,INS5_rep3,INS5_rep4,INS90_rep1,INS90_rep2,INS90_rep3,INS90_rep4,starve_rep1,starve_rep2,starve_rep3,starve_rep4
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,light,NaN,9390.509131,NaN,...,NaN,NaN,NaN,16649.617758,NaN,NaN,NaN,11970.095745,NaN,NaN
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,light,340538.501674,253199.526477,345661.537241,...,640068.892343,609313.992354,1.101519e+06,978459.436634,739168.734854,654271.083466,462877.845884,406460.086218,466606.366000,546126.385146
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,light,234295.305125,224980.708881,249750.746679,...,352464.054481,292555.820093,3.046746e+05,281502.004865,183240.972340,193311.671129,370294.907420,351169.823470,391574.055743,362341.166440
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,light,NaN,24388.962715,NaN,...,NaN,32395.739650,NaN,31173.598955,NaN,27815.338181,NaN,36947.507319,NaN,47420.988126
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,light,389822.380650,394874.312844,446987.460034,...,548273.689794,NaN,5.041867e+05,417220.990719,290892.691327,NaN,732858.964004,703950.993495,706990.737660,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0,False,False,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,light,25252.990648,26286.954697,24405.755392,...,33097.506993,28395.721174,2.376186e+04,28084.344438,21065.836252,26432.894157,28158.918559,31337.999945,38445.424548,33814.648783
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0,False,False,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,light,NaN,NaN,NaN,...,NaN,22027.613058,NaN,NaN,NaN,17277.494964,NaN,NaN,NaN,28097.874460
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0,False,False,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,light,140677.746816,181019.596640,172591.396944,...,231792.162913,187932.034007,1.959795e+05,183652.169633,156946.276704,150189.186015,202512.144807,165807.326109,237987.604392,259115.655994
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8,False,False,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,light,NaN,NaN,2917.965774,...,5013.201688,NaN,NaN,NaN,3158.336293,NaN,NaN,NaN,5253.875296,NaN
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8,False,False,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,light,58246.073008,63487.353398,NaN,...,NaN,NaN,1.008680e+05,71599.215405,NaN,NaN,94711.843842,83686.478536,NaN,NaN

## Log2 transformation

In [164]:
columns = raw_abundances.columns
log2_transformed_df = pd.DataFrame(columns=columns)

for row in raw_abundances.itertuples():
    row_list=[]
    index= row[0]
    for element in row:
        if type(element) == float:
            log2 = np.log2(element)
            row_list.append(log2)
        else:
            row_list.append(element)
        # print(row_list[1:])
        # print(log2_transformed_df.columns)
    log2_transformed_df.loc[len(log2_transformed_df)] = row_list[1:]
    
log2_transformed_df.to_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_Log2.xlsx", index=False)
log2_transformed_df

,protein_ID,prot_name,IDcolumn,CON,REV,site,isotopeLabel,EGFnINS1_rep1,EGFnINS1_rep2,EGFnINS1_rep3,...,INS5_rep3,INS5_rep4,INS90_rep1,INS90_rep2,INS90_rep3,INS90_rep4,starve_rep1,starve_rep2,starve_rep3,starve_rep4
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,light,NaN,13.196988,NaN,...,NaN,NaN,NaN,14.023201,NaN,NaN,NaN,13.547147,NaN,NaN
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,light,18.377458,17.949915,18.399001,...,19.287868,19.216826,20.071062,19.900153,19.495544,19.319529,18.820272,18.632754,18.831846,19.058875
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,light,17.837969,17.779442,17.930129,...,18.427117,18.158352,18.216910,18.102786,17.483383,17.560569,18.498315,18.421809,18.578926,18.466989
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,light,NaN,14.573941,NaN,...,NaN,14.983516,NaN,14.928037,NaN,14.763593,NaN,15.173189,NaN,15.533238
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2,False,False,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,light,18.572457,18.591034,18.769875,...,19.064537,NaN,18.943599,18.670452,18.150128,NaN,19.483176,19.425115,19.431332,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0,False,False,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,light,14.624167,14.682059,14.574934,...,15.014435,14.793386,14.536360,14.777479,14.362618,14.690047,14.781304,14.935625,15.230524,15.045361
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0,False,False,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,light,NaN,NaN,NaN,...,NaN,14.427026,NaN,NaN,NaN,14.076606,NaN,NaN,NaN,14.778173
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0,False,False,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,light,17.102035,17.465786,17.397001,...,17.822472,17.519851,17.580343,17.486616,17.259911,17.196421,17.627649,17.339148,17.860527,17.983237
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8,False,False,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,light,NaN,NaN,11.510747,...,12.291517,NaN,NaN,NaN,11.624949,NaN,NaN,NaN,12.359166,NaN
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8,False,False,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,light,15.829873,15.954182,NaN,...,NaN,NaN,16.622109,16.127656,NaN,NaN,16.531257,16.352707,NaN,NaN

## Calculating average of the log2 transformed data

In [1]:
log2_transformed_df=log2_transformed_df.fillna(0)

EGF = {'EGF1' : ["EGF1_rep1", 'EGF1_rep2', "EGF1_rep3", "EGF1_rep4"], 
       'EGF2' : ["EGF2_rep1", 'EGF2_rep2', "EGF2_rep3", "EGF2_rep4"],
       'EGF5' : ["EGF5_rep1", 'EGF5_rep2', "EGF5_rep3", "EGF5_rep4"], 
       'EGF10' : ["EGF10_rep1", 'EGF10_rep2', "EGF10_rep3", "EGF10_rep4"], 
       'EGF90' : ["EGF90_rep1", 'EGF90_rep2', "EGF90_rep3", "EGF90_rep4"]}
INS = {'INS1' : ["INS1_rep1", "INS1_rep2", "INS1_rep3", "INS1_rep4"], 
       'INS2' : ["INS2_rep1", "INS2_rep2", "INS2_rep3", "INS2_rep4"], 
       'INS5' : ["INS5_rep1", "INS5_rep2", "INS5_rep3", "INS5_rep4"], 
       'INS10' : ["INS10_rep1", "INS10_rep2", "INS10_rep3", "INS10_rep4"], 
       'INS90' : ["INS90_rep1", "INS90_rep2", "INS90_rep3", "INS90_rep4"]}
EGFnINS = {'EGFnINS1' : ["EGFnINS1_rep1", 'EGFnINS1_rep2', "EGFnINS1_rep3", "EGFnINS1_rep4"], 
           'EGFnINS2' : ["EGFnINS2_rep1", 'EGFnINS2_rep2', "EGFnINS2_rep3", "EGFnINS2_rep4"],
           'EGFnINS5' : ["EGFnINS5_rep1", 'EGFnINS5_rep2', "EGFnINS5_rep3", "EGFnINS5_rep4"], 
           'EGFnINS10' : ["EGFnINS10_rep1", 'EGFnINS10_rep2', "EGFnINS10_rep3", "EGFnINS10_rep4"], 
           'EGFnINS90' : ["EGFnINS90_rep1", 'EGFnINS90_rep2', "EGFnINS90_rep3", "EGFnINS90_rep4"]}
starvation = ["starve_rep1", "starve_rep2", "starve_rep3", "starve_rep4"]
full = ["full_rep1", "full_rep2", "full_rep3", "full_rep4"]

columns = ["protein_ID", "prot_name", "site", 
           "full_log2_avg", "starvation_log2_avg",
           "EGF1_log2_avg", "EGF2_log2_avg", "EGF5_log2_avg", "EGF10_log2_avg", "EGF90_log2_avg", 
           "INS1_log2_avg", "INS2_log2_avg", "INS5_log2_avg", "INS10_log2_avg", "INS90_log2_avg", 
           "EGFnINS1_log2_avg", "EGFnINS2_log_avg", "EGFnINS5_log_avg", "EGFnINS10_log_avg", "EGFnINS90_log_avg",
           "full_log2_std", "starvation_log2_std",
           "EGF1_log2_std", "EGF2_log2_std", "EGF5_log2_std", "EGF10_log2_std", "EGF90_log2_std", 
           "INS1_log2_std", "INS2_log2_std", "INS5_log2_std", "INS10_log2_std", "INS90_log2_std", 
           "EGFnINS1_log2_std", "EGFnINS2_log_std", "EGFnINS5_log_std", "EGFnINS10_log_std", "EGFnINS90_log_std",
           "full_log2_cv", "starvation_log2_cv",
           "EGF1_log2_cv", "EGF2_log2_cv", "EGF5_log2_cv", "EGF10_log2_cv", "EGF90_log2_cv", 
           "INS1_log2_cv", "INS2_log2_cv", "INS5_log2_cv", "INS10_log2_cv", "INS90_log2_cv", 
           "EGFnINS1_log2_cv", "EGFnINS2_log_cv", "EGFnINS5_log_cv", "EGFnINS10_log_cv", "EGFnINS90_log_cv", "n_reps"]

avg_log2_df = pd.DataFrame(columns = columns)

for row in log2_transformed_df.iterrows():
    phospho_info = []
    mean_list =[]
    std_list = []
    cv_list = []
    phospho_info.append(row[1]['protein_ID'])
    phospho_info.append(row[1]['prot_name'])
    phospho_info.append(row[1]['site'])
    
    full_values_list = []
    for replicate in full:
        value = row[1][replicate]
        full_values_list.append(value)
    while 0 in full_values_list:
        full_values_list.remove(0)
    full_values_mean = np.mean(full_values_list)
    mean_list.append(full_values_mean)
    full_values_std = np.std(full_values_list)
    std_list.append(full_values_std)
    full_values_cv = (full_values_std / full_values_mean) * 100
    cv_list.append(full_values_cv)
    n_reps = [len(full_values_list)]
        
    starvation_values_list = []
    for replicate in starvation:
        value = row[1][replicate]
        starvation_values_list.append(value)
    while 0 in starvation_values_list:
        starvation_values_list.remove(0)
    starvation_values_mean = np.mean(starvation_values_list)
    mean_list.append(starvation_values_mean)
    starvation_values_std = np.std(starvation_values_list)
    std_list.append(starvation_values_std)
    starvation_values_cv = (starvation_values_std / starvation_values_mean) * 100
    cv_list.append(starvation_values_cv)
        
    for key in EGF:
        EGF_values_list = []
        for replicate in EGF[key]:
            value = row[1][replicate]
            EGF_values_list.append(value)
        while 0 in EGF_values_list:
            EGF_values_list.remove(0)
        EGF_values_mean = np.mean(EGF_values_list)
        mean_list.append(EGF_values_mean)
        EGF_values_std = np.std(EGF_values_list)
        std_list.append(EGF_values_std)
        EGF_values_cv = (EGF_values_std / EGF_values_mean) * 100
        cv_list.append(EGF_values_cv)
        
    for key in INS:
        INS_values_list = []
        for replicate in INS[key]:
            value = row[1][replicate]
            INS_values_list.append(value)
        while 0 in INS_values_list:
            INS_values_list.remove(0)
        INS_values_mean = np.mean(INS_values_list)
        mean_list.append(INS_values_mean)
        INS_values_std = np.std(INS_values_list)
        std_list.append(INS_values_std)
        INS_values_cv = (INS_values_std / INS_values_mean) * 100
        cv_list.append(INS_values_cv)
        
    for key in EGFnINS:
        EGFnINS_values_list = []
        for replicate in EGFnINS[key]:
            value = row[1][replicate]
            EGFnINS_values_list.append(value)
        while 0 in EGFnINS_values_list:
            EGFnINS_values_list.remove(0)
        EGFnINS_values_mean = np.mean(EGFnINS_values_list)
        mean_list.append(EGFnINS_values_mean)
        EGFnINS_values_std = np.std(EGFnINS_values_list)
        std_list.append(EGFnINS_values_std)
        EGFnINS_values_cv = (EGFnINS_values_std / EGFnINS_values_mean) * 100
        cv_list.append(EGFnINS_values_cv)
        
    row_list = phospho_info + mean_list + std_list + cv_list + n_reps
    
    avg_log2_df.loc[len(avg_log2_df)] = row_list

    # print(row_list, len(row_list))
    
    
avg_log2_df.to_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_avg_log2.xlsx", index=False)
avg_log2_df

NameError: name 'log2_transformed_df' is not defined

## Calculate the fold change respect the starvation time point

In [166]:
columns_FC = ["protein_ID", "prot_name", "site", 
              "EGF_full", "EGF_starve",
              "EGF1", "EGF2", "EGF5", "EGF10", "EGF90", 
              "INS_full", "INS_starve",
              "INS1", "INS2", "INS5", "INS10", "INS90", 
              "EGFnINS_full", "EGFnINS_starve",
              "EGFnINS1", "EGFnINS2", "EGFnINS5", "EGFnINS10", "EGFnINS90", 
              "n_reps", "sd_all",
              "EGF_full_std", "EGF_starve_std",
              "EGF1_std", "EGF2_std", "EGF5_std", "EGF10_std", "EGF90_std", 
              "INS_full_std", "INS_starve_std",
              "INS1_std", "INS2_std", "INS5_std", "INS10_std", "INS90_std", 
              "EGFnINS_full_std", "EGFnINS_starve_std",
              "EGFnINS1_std", "EGFnINS2_std", "EGFnINS5_std", "EGFnINS10_std", "EGFnINS90_std" ]
# print(len(columns_FC))

log2_FC_df = pd.DataFrame(columns = columns_FC)
for row in avg_log2_df.iterrows():
    phospho_FC = []
    phospho_FC.append(row[1]['protein_ID'])
    phospho_FC.append(row[1]['prot_name'])
    phospho_FC.append(row[1]['site'])
    
    condition_list = ["full_log2_avg", "starvation_log2_avg",
                      "EGF1_log2_avg", "EGF2_log2_avg", "EGF5_log2_avg", "EGF10_log2_avg", "EGF90_log2_avg", 
                      "full_log2_avg", "starvation_log2_avg",
                      "INS1_log2_avg", "INS2_log2_avg", "INS5_log2_avg", "INS10_log2_avg", "INS90_log2_avg", 
                      "full_log2_avg", "starvation_log2_avg",
                      "EGFnINS1_log2_avg", "EGFnINS2_log_avg", "EGFnINS5_log_avg", "EGFnINS10_log_avg", "EGFnINS90_log_avg"]
    
    for condition in condition_list:
        fold_change = row[1][condition] - row[1]['starvation_log2_avg'] 
        phospho_FC.append(fold_change)
    
    phospho_FC.append(row[1]["n_reps"])
    phospho_FC.append("NaN")
    std_list = ["full_log2_std", "starvation_log2_std",
                "EGF1_log2_std", "EGF2_log2_std", "EGF5_log2_std", "EGF10_log2_std", "EGF90_log2_std", 
                "full_log2_std", "starvation_log2_std",
                "INS1_log2_std", "INS2_log2_std", "INS5_log2_std", "INS10_log2_std", "INS90_log2_std", 
                "full_log2_std", "starvation_log2_std",
                "EGFnINS1_log2_std", "EGFnINS2_log_std", "EGFnINS5_log_std", "EGFnINS10_log_std", "EGFnINS90_log_std",]
    for std in std_list:
        phospho_FC.append(row[1][std])
    
    # print(len(phospho_FC))
    log2_FC_df.loc[len(log2_FC_df)] = phospho_FC
    
log2_FC_df.to_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_Log2_FC.xlsx", index=False)
log2_FC_df

,protein_ID,prot_name,site,EGF_full,EGF_starve,EGF1,EGF2,EGF5,EGF10,EGF90,...,INS5_std,INS10_std,INS90_std,EGFnINS_full_std,EGFnINS_starve_std,EGFnINS1_std,EGFnINS2_std,EGFnINS5_std,EGFnINS10_std,EGFnINS90_std
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,1.511860,0.0,-0.307085,-0.306726,-0.272023,-0.179460,0.275051,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,2.592063,0.0,-0.197484,-0.129022,0.486223,0.771928,0.339785,...,0.118626,0.078214,0.301770,0.106089,0.151036,0.267469,0.202585,0.112555,0.248812,0.072220
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,-0.632162,0.0,-0.175607,-0.350557,-0.278136,-0.484259,-0.723521,...,0.140662,0.130458,0.322634,0.230423,0.057331,0.112945,0.119324,0.145600,0.266767,0.128188
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,-0.339537,0.0,-0.042816,-0.146023,-0.109980,-0.447046,-0.159981,...,0.208711,0.052691,0.082222,0.055029,0.180024,0.278058,0.203869,0.400614,0.516101,0.089041
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,-0.868938,0.0,-0.255034,-0.575410,-0.642057,-0.814150,-0.994097,...,0.106832,0.181420,0.329131,0.320137,0.026029,0.089009,0.188807,0.178750,0.222757,0.161914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,-0.106393,0.0,-0.010890,-0.172770,-0.007198,-0.282957,-0.226106,...,0.120500,0.157839,0.157898,0.255491,0.163675,0.040996,0.107383,0.154037,0.202717,0.059075
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,-0.498047,0.0,-0.109026,-0.240676,-0.160604,-0.388431,-0.430565,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,-0.063809,0.0,-0.118702,-0.094026,-0.045941,-0.287273,-0.150436,...,0.120985,0.048657,0.157816,0.241093,0.245669,0.138297,0.207605,0.128408,0.270076,0.158136
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,-0.510144,0.0,-0.282727,-0.217939,0.210960,-0.008441,-0.199922,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,-0.005536,0.0,-0.154411,-0.309065,0.018459,-0.192843,0.154931,...,0.431999,0.054144,0.247226,0.280349,0.089275,0.062154,0.183084,0.303695,0.359326,0.167237

## Calculate the fold change respect the starvation but using the data already processed by the FGCZ

In [167]:
df_fgcz = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/Renamed.xlsx", sheet_name="stats_normalized_wide")

columns_FC = ["protein_ID", "site",  #, "prot_name"
              "EGF_full", "EGF_starve", 
              "EGF1", "EGF2", "EGF5", "EGF10", "EGF90", 
              "INS_full", "INS_starve",
              "INS1", "INS2", "INS5", "INS10", "INS90", 
              "EGFnINS_full", "EGFnINS_starve",
              "EGFnINS1", "EGFnINS2", "EGFnINS5", "EGFnINS10", "EGFnINS90", 
              "n_reps", "sd_all",
              "EGF_full_std", "EGF_starve_std",
              "EGF1_std", "EGF2_std", "EGF5_std", "EGF10_std", "EGF90_std", 
              "INS_full_std", "INS_starve_std",
              "INS1_std", "INS2_std", "INS5_std", "INS10_std", "INS90_std", 
              "EGFnINS_full_std", "EGFnINS_starve_std",
              "EGFnINS1_std", "EGFnINS2_std", "EGFnINS5_std", "EGFnINS10_std", "EGFnINS90_std" ]

log2_FC_df_fgcz = pd.DataFrame(columns = columns_FC)
for row in df_fgcz.iterrows():
    phospho_FC = []
    phospho_FC.append(row[1]['protein_Id'])
    # phospho_FC.append(row[1]['prot_name'])
    phospho_FC.append(row[1]['site'])
    
    condition_list = ["mean_full", "mean_starve",
                      "mean_EGF1", "mean_EGF2", "mean_EGF5", "mean_EGF10", "mean_EGF90", 
                      "mean_full", "mean_starve",
                      "mean_INS1", "mean_INS2", "mean_INS5", "mean_INS10", "mean_INS90", 
                      "mean_full", "mean_starve",
                      "mean_EGFnINS1", "mean_EGFnINS2", "mean_EGFnINS5", "mean_EGFnINS10", "mean_EGFnINS90"]
    
    for condition in condition_list:
        fold_change = row[1][condition] - row[1]['mean_starve'] 
        phospho_FC.append(fold_change)
    
    phospho_FC.append(row[1]["not_na_starve"])
    phospho_FC.append(row[1]["sd_All"])
    std_list = ["sd_full", "sd_starve",
                "sd_EGF1", "sd_EGF2", "sd_EGF5", "sd_EGF10", "sd_EGF90", 
                "sd_full", "sd_starve",
                "sd_INS1", "sd_INS2", "sd_INS5", "sd_INS10", "sd_INS90", 
                "sd_full", "sd_starve",
                "sd_EGFnINS1", "sd_EGFnINS2", "sd_EGFnINS5", "sd_EGFnINS10", "sd_EGFnINS90",]
    for std in std_list:
        phospho_FC.append(row[1][std])
    
    # print(len(phospho_FC))
    log2_FC_df_fgcz.loc[len(log2_FC_df_fgcz)] = phospho_FC
    

prot_name_df = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/Renamed.xlsx", sheet_name="normalized_abundances_matrix")


prot_name_dir = {}
for row in prot_name_df.itertuples():
    protein_ID = row[1]
    prot_name = row[2]
    prot_name_dir[protein_ID] = prot_name

log2_FC_df_fgcz.insert(1, "prot_name", 0)
for row in log2_FC_df_fgcz.itertuples():
    index = row[0]
    id = row[1]
    log2_FC_df_fgcz.at[index, 'prot_name'] = prot_name_dir[id]

log2_FC_df_fgcz.to_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_Log2_FC_from_FGZC.xlsx", index=False)

/var/folders/3x/34lr70ks7312krzcy07d2900gmckg0/T/ipykernel_51385/2450202274.py:64: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'HNRNPA1L3' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  log2_FC_df_fgcz.at[index, 'prot_name'] = prot_name_dir[id]