# TPS file creator

This code will be used to transform our time series data in the right format to be able to run the Temporal Pathway Synthesizer [TPS](https://github.com/koksal/tps.git).

I am going to create separated files for EGF, INS and EGFnINS

In [7]:
import pandas as pd
import numpy as np
from pandas.core.indexes.base import maybe_extract_name

## Time series file

1.  Calculate means of the abundances
2. Filter for at least 2 repetitions and all phosphorilations found (use code in Data_filtration_and _processing)
3. Create individual files for each stimulation condition and refactor columns (these files only contain phosphosite and time points means). Save them as **.tsv**

In [15]:
raw_abundances = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/Renamed.xlsx", sheet_name="raw_abundances_matrix")
raw_abundances.fillna(0, inplace=True)

EGF = {'EGF1' : ["EGF1_rep1", 'EGF1_rep2', "EGF1_rep3", "EGF1_rep4"], 
       'EGF2' : ["EGF2_rep1", 'EGF2_rep2', "EGF2_rep3", "EGF2_rep4"],
       'EGF5' : ["EGF5_rep1", 'EGF5_rep2', "EGF5_rep3", "EGF5_rep4"], 
       'EGF10' : ["EGF10_rep1", 'EGF10_rep2', "EGF10_rep3", "EGF10_rep4"], 
       'EGF90' : ["EGF90_rep1", 'EGF90_rep2', "EGF90_rep3", "EGF90_rep4"]}
INS = {'INS1' : ["INS1_rep1", "INS1_rep2", "INS1_rep3", "INS1_rep4"], 
       'INS2' : ["INS2_rep1", "INS2_rep2", "INS2_rep3", "INS2_rep4"], 
       'INS5' : ["INS5_rep1", "INS5_rep2", "INS5_rep3", "INS5_rep4"], 
       'INS10' : ["INS10_rep1", "INS10_rep2", "INS10_rep3", "INS10_rep4"], 
       'INS90' : ["INS90_rep1", "INS90_rep2", "INS90_rep3", "INS90_rep4"]}
EGFnINS = {'EGFnINS1' : ["EGFnINS1_rep1", 'EGFnINS1_rep2', "EGFnINS1_rep3", "EGFnINS1_rep4"], 
           'EGFnINS2' : ["EGFnINS2_rep1", 'EGFnINS2_rep2', "EGFnINS2_rep3", "EGFnINS2_rep4"],
           'EGFnINS5' : ["EGFnINS5_rep1", 'EGFnINS5_rep2', "EGFnINS5_rep3", "EGFnINS5_rep4"], 
           'EGFnINS10' : ["EGFnINS10_rep1", 'EGFnINS10_rep2', "EGFnINS10_rep3", "EGFnINS10_rep4"], 
           'EGFnINS90' : ["EGFnINS90_rep1", 'EGFnINS90_rep2', "EGFnINS90_rep3", "EGFnINS90_rep4"]}
starvation = ["starve_rep1", "starve_rep2", "starve_rep3", "starve_rep4"]
full = ["full_rep1", "full_rep2", "full_rep3", "full_rep4"]

columns = ["protein_ID", "prot_name", "site", 
           "full_mean", "starvation_mean",
           "EGF1_mean", "EGF2_mean", "EGF5_mean", "EGF10_mean", "EGF90_mean", 
           "INS1_mean", "INS2_mean", "INS5_mean", "INS10_mean", "INS90_mean", 
           "EGFnINS1_mean", "EGFnINS2_mean", "EGFnINS5_mean", "EGFnINS10_mean", "EGFnINS90_mean",
           "n_reps"] 
           

mean_df = pd.DataFrame(columns = columns)


for row in raw_abundances.iterrows():
    phospho_info = []
    mean_list =[]
    phospho_info.append(row[1]['protein_ID'])
    phospho_info.append(row[1]['prot_name'])
    phospho_info.append(row[1]['site'])
    
    full_values_list = []
    for replicate in full:
        value = row[1][replicate]
        full_values_list.append(value)
    while 0 in full_values_list:
        full_values_list.remove(0)
    full_values_mean = np.mean(full_values_list)
    mean_list.append(full_values_mean)
    n_reps = [len(full_values_list)]
        
    starvation_values_list = []
    for replicate in starvation:
        value = row[1][replicate]
        starvation_values_list.append(value)
    while 0 in starvation_values_list:
        starvation_values_list.remove(0)
    starvation_values_mean = np.mean(starvation_values_list)
    mean_list.append(starvation_values_mean)
        
    for key in EGF:
        EGF_values_list = []
        for replicate in EGF[key]:
            value = row[1][replicate]
            EGF_values_list.append(value)
        while 0 in EGF_values_list:
            EGF_values_list.remove(0)
        EGF_values_mean = np.mean(EGF_values_list)
        mean_list.append(EGF_values_mean)
        
    for key in INS:
        INS_values_list = []
        for replicate in INS[key]:
            value = row[1][replicate]
            INS_values_list.append(value)
        while 0 in INS_values_list:
            INS_values_list.remove(0)
        INS_values_mean = np.mean(INS_values_list)
        mean_list.append(INS_values_mean)
        
    for key in EGFnINS:
        EGFnINS_values_list = []
        for replicate in EGFnINS[key]:
            value = row[1][replicate]
            EGFnINS_values_list.append(value)
        while 0 in EGFnINS_values_list:
            EGFnINS_values_list.remove(0)
        EGFnINS_values_mean = np.mean(EGFnINS_values_list)
        mean_list.append(EGFnINS_values_mean)
        
    row_list = phospho_info + mean_list + n_reps # std_list + cv_list + n_reps
    # print(len(row_list), len(columns))
    mean_df.loc[len(mean_df)] = row_list
    # print(row_list, len(row_list))
    
# mean_df.to_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_abs_mean_nreps.xlsx", index=False)
# mean_df

/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

,protein_ID,prot_name,site,full_mean,starvation_mean,EGF1_mean,EGF2_mean,EGF5_mean,EGF10_mean,EGF90_mean,...,INS2_mean,INS5_mean,INS10_mean,INS90_mean,EGFnINS1_mean,EGFnINS2_mean,EGFnINS5_mean,EGFnINS10_mean,EGFnINS90_mean,n_reps
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,3.413601e+04,11970.095745,9675.108661,9677.517058,9913.122742,10569.994951,14484.260255,...,8318.849374,13163.288457,12343.184416,16649.617758,9390.509131,13538.851396,10706.525757,2.048964e+04,1.591420e+04,1
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,2.829023e+06,470517.670812,410572.566544,435013.860584,664260.446844,806011.296406,597757.345440,...,407369.107604,579085.266748,715733.934494,868354.446993,341378.901918,439804.154582,659377.648646,1.028321e+06,1.086652e+06,4
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,2.407927e+05,368844.988268,328178.085530,289900.761657,307759.341321,264812.280393,224670.497256,...,296411.976424,300312.077507,288465.828566,240682.305193,246463.477066,289305.801951,268420.144179,2.950741e+05,2.019919e+05,4
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,3.310419e+04,42184.247722,40811.273936,37939.493868,39732.078138,31261.173339,38101.769865,...,31153.822756,37830.753799,35834.133878,29494.468568,30124.096929,42893.119322,30546.822953,5.727112e+04,3.013388e+04,2
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,4.007939e+05,714600.231720,600688.370186,479812.518176,463692.500253,409202.106674,360732.854217,...,492272.278880,515925.794156,460984.696446,404100.136027,410561.384509,483925.264631,403141.056566,4.599591e+05,3.413294e+05,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,3.086557e+04,32939.247959,32676.235818,29132.919786,32756.590744,27137.794214,28298.985990,...,31007.808005,29583.489496,28534.233440,24836.234833,25472.173674,26132.881046,25722.986370,2.964300e+04,2.740820e+04,4
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,1.989511e+04,28097.874460,26052.730401,23780.595407,25137.773909,21465.649043,20847.811615,...,22549.888280,22027.613058,22851.411938,17277.494964,20086.097858,21717.337880,18335.232250,2.028096e+04,1.819115e+04,1
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,2.069728e+05,216355.682825,197700.371530,200797.240615,207220.546658,175866.397068,194120.441113,...,187333.256170,203741.022298,214293.539254,171691.780289,165945.592427,185395.451170,163866.552589,2.097088e+05,1.724802e+05,4
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,3.689021e+03,5253.875296,4318.874565,4517.243369,6081.142165,5223.226681,4574.010680,...,4692.521784,5013.201688,4739.520518,3158.336293,2917.965774,3689.312455,3552.624994,4.001188e+03,3.109973e+03,1
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,9.036743e+04,89199.161189,81746.548569,72421.030262,90349.441195,78189.392672,100027.791351,...,79429.320740,120887.597466,75766.691638,86233.603063,60866.713203,92346.923414,75921.485201,9.383952e+04,8.739716e+04,2

In [17]:
filtered_df = pd.read_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_abs_mean_nRep1_allPhosphoFound_True.xlsx")

EGF_columns = ["site", "full_mean", "starvation_mean", "EGF1_mean", "EGF2_mean", "EGF5_mean", "EGF10_mean", "EGF90_mean"]
INS_columns = ["site", "full_mean", "starvation_mean", "INS1_mean", "INS2_mean", "INS5_mean", "INS10_mean", "INS90_mean"]
EGFnINS_columns = ["site", "full_mean", "starvation_mean", "EGFnINS1_mean", "EGFnINS2_mean", "EGFnINS5_mean", "EGFnINS10_mean", "EGFnINS90_mean"]

EGF_time_series = filtered_df[EGF_columns]
EGF_time_series.rename(columns={"full_mean" : "0min", 
                                "starvation_mean" : "120min",
                                "EGF1_mean" : "121min",
                                "EGF2_mean" : "122min",
                                "EGF5_mean" : "125min",
                                "EGF10_mean" : "130min",
                                "EGF90_mean" : "210min"}, inplace=True)
EGF_time_series.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/EGF_time_series.tsv", sep="\t", index=False)

INS_time_series = filtered_df[INS_columns]
INS_time_series.rename(columns={"full_mean" : "0min", 
                                "starvation_mean" : "120min",
                                "INS1_mean" : "121min",
                                "INS2_mean" : "122min",
                                "INS5_mean" : "125min",
                                "INS10_mean" : "130min",
                                "INS90_mean" : "210min"}, inplace=True)
INS_time_series.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/INS_time_series.tsv", sep="\t", index=False)

EGFnINS_time_series = filtered_df[EGFnINS_columns]
EGFnINS_time_series.rename(columns={"full_mean" : "0min", 
                                "starvation_mean" : "120min",
                                "EGFnINS1_mean" : "121min",
                                "EGFnINS2_mean" : "122min",
                                "EGFnINS5_mean" : "125min",
                                "EGFnINS10_mean" : "130min",
                                "EGFnINS90_mean" : "210min"}, inplace=True)
EGFnINS_time_series.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/EGFnINS_time_series.tsv", sep="\t", index=False)

EGF_time_series_no_full = EGF_time_series.drop(["0min"], axis=1)
EGF_time_series_no_full.rename(columns={"120min" : "0min",
                                            "121min" : "1min", 
                                            "122min" : "2min",
                                            "125min" : "5min",
                                            "130min" : "10min",
                                            "210min" : "90min"}, inplace=True)
EGF_time_series_no_full.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/EGF_time_series_no_full.tsv", sep="\t", index=False)

INS_time_series_no_full = INS_time_series.drop(["0min"], axis=1)
INS_time_series_no_full.rename(columns={"120min" : "0min",
                                            "121min" : "1min", 
                                            "122min" : "2min",
                                            "125min" : "5min",
                                            "130min" : "10min",
                                            "210min" : "90min"}, inplace=True)
INS_time_series_no_full.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/INS_time_series_no_full.tsv", sep="\t", index=False)

EGFnINS_time_series_no_full = EGFnINS_time_series.drop(["0min"], axis=1)
EGFnINS_time_series_no_full.rename(columns={"120min" : "0min",
                                            "121min" : "1min", 
                                            "122min" : "2min",
                                            "125min" : "5min",
                                            "130min" : "10min",
                                            "210min" : "90min"}, inplace=True)
EGFnINS_time_series_no_full.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/EGFnINS_time_series_no_full.tsv", sep="\t", index=False)

,protein_ID,prot_name,site,full_mean,starvation_mean,EGF1_mean,EGF2_mean,EGF5_mean,EGF10_mean,EGF90_mean,...,INS2_mean,INS5_mean,INS10_mean,INS90_mean,EGFnINS1_mean,EGFnINS2_mean,EGFnINS5_mean,EGFnINS10_mean,EGFnINS90_mean,n_reps
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,2.829023e+06,470517.670812,410572.566544,435013.860584,664260.446844,806011.296406,597757.345440,...,407369.107604,579085.266748,715733.934494,868354.446993,341378.901918,439804.154582,659377.648646,1.028321e+06,1.086652e+06,4
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,3.310419e+04,42184.247722,40811.273936,37939.493868,39732.078138,31261.173339,38101.769865,...,31153.822756,37830.753799,35834.133878,29494.468568,30124.096929,42893.119322,30546.822953,5.727112e+04,3.013388e+04,2
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,4.007939e+05,714600.231720,600688.370186,479812.518176,463692.500253,409202.106674,360732.854217,...,492272.278880,515925.794156,460984.696446,404100.136027,410561.384509,483925.264631,403141.056566,4.599591e+05,3.413294e+05,3
3,A0A3B3IU46,RAMACL,A0A3B3IU46_36_45_1_1_S36~RPPEsPPIVEEWNSR,1.135118e+05,126906.365791,117335.944069,117439.970358,125215.573616,113902.107808,106176.762161,...,123834.012844,117808.623795,111192.539304,97500.357233,101842.513491,94554.121385,90768.225120,9.494259e+04,1.056203e+05,2
4,A0AVK6,E2F8,A0AVK6_52_60_1_1_T58~EGSQGEPWtPTANLK,3.716773e+04,37213.287512,32405.924406,32938.224202,39008.311172,33600.469355,38595.647599,...,30371.004056,35950.089694,33275.326653,31424.006473,27865.205445,32229.333108,33287.200371,3.530759e+04,3.459214e+04,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16299,Q9Y6X9,MORC2,Q9Y6X9_773_785_1_1_S779~KDSNELSDsAGEEDSADLKR,9.471837e+04,105809.683305,87331.602428,84771.691136,87262.801291,75229.494350,99737.839286,...,77943.939465,95767.773558,92950.123303,85173.662381,76409.398514,93235.760613,72332.111096,1.046429e+05,8.243666e+04,2
16300,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_246_246_1_1_S246~LLDGNLLDGQAEVFGsDDDHIQ...,1.075838e+05,135628.147619,132195.829987,127590.831421,129911.768739,117107.903043,113146.073571,...,121766.791089,120550.767706,132768.601679,103263.756242,103143.608619,106657.668107,105142.001348,1.169367e+05,1.014045e+05,4
16301,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,3.086557e+04,32939.247959,32676.235818,29132.919786,32756.590744,27137.794214,28298.985990,...,31007.808005,29583.489496,28534.233440,24836.234833,25472.173674,26132.881046,25722.986370,2.964300e+04,2.740820e+04,4
16302,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,2.069728e+05,216355.682825,197700.371530,200797.240615,207220.546658,175866.397068,194120.441113,...,187333.256170,203741.022298,214293.539254,171691.780289,165945.592427,185395.451170,163866.552589,2.097088e+05,1.724802e+05,4
16303,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,9.036743e+04,89199.161189,81746.548569,72421.030262,90349.441195,78189.392672,100027.791351,...,79429.320740,120887.597466,75766.691638,86233.603063,60866.713203,92346.923414,75921.485201,9.383952e+04,8.739716e+04,2

## Network file

Protein protein interaction network on which the pathway will be written. 

I am going to take the PPI map form EGFR from string. There are several of these file in th string folder, lets start with the small one

In [41]:
EGFR_string_interactome = pd.read_csv("External_Data/String/EGFR_downregulation_string_interactions.tsv", sep="\t")
EGFR_interactome = EGFR_string_interactome[["#node1", "node2"]].copy()
EGFR_interactome.columns.name = None
# EGFR_interactome.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/EGFR_downregulation_interactome.tsv", sep="\t", index=False) # I HAD TO REMOVE THE FORST ROW MANUALLY

## Peptide map

site and protein it belongs to

In [56]:
mapping = pd.read_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_abs_mean_nRep1_allPhosphoFound_True.xlsx")
peptide_map = mapping[["site", "prot_name"]].copy()
peptide_map.rename(columns={"site": "peptide",
                            "prot_name":"protein(s)"}, inplace=True)
peptide_map.to_csv("Experiment/1_hTERT_HME1/Data/Processed/tps_files/peptide_map.tsv", sep="\t", index=False)

## First scores

Calculate the significance scores respect starvation (0min)